[deploy]
startCommand = 'sh -c "npm install -g \"$CUSTOM_NPM_GLOBAL_PACKAGES\" && n8n start"'
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 8
