[deploy]
startCommand = 'bash -c "npm install -g \"$CUSTOM_NPM_GLOBAL_PACKAGES\" && n8n start"'
healthcheckPath = "/healthz"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 8
