[deploy]
startCommand = 'bash -c "cd /home/node && npm install cheerio lodash && n8n start"'
healthcheckPath = "/healthz"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 8
