[deploy]
startCommand = 'bash -c "cd /usr/local/lib/node_modules/n8n && npm install cheerio lodash && n8n start"'
healthcheckPath = "/healthz"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 8
